CREATE TABLE `stock_dfcf_fund_flow_info` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键',
  `stock_market` varchar(32) DEFAULT NULL COMMENT '股市名',
  `stock_rank` varchar(32) DEFAULT NULL COMMENT '排行榜名',
  `stock_code` varchar(64) DEFAULT NULL COMMENT '股票代码',
  `stock_name` varchar(64) DEFAULT NULL COMMENT '股票名字',
  `price_new` decimal(12,3) DEFAULT NULL COMMENT '股票最新价格',
  `stock_change` decimal(6,2) DEFAULT NULL COMMENT '涨跌幅',
  `main_net_inflow_amount` decimal(12,4) DEFAULT NULL COMMENT '主力净额,净流入,主力流入：超大单加大单买入成交额之和',
  `main_net_proportion` decimal(5,2) DEFAULT NULL COMMENT '主力净流入--净占比',
  `super_big_part_net_inFlow_amount` decimal(12,4) DEFAULT NULL COMMENT '超大单净额,净流入,超大单：大于等于50万股或者100万元的成交单',
  `super_big_part_net_proportion` decimal(5,2) DEFAULT NULL COMMENT '超大单净流入--净占比',
  `big_part_net_inFlow_amount` decimal(12,4) DEFAULT NULL COMMENT '大单净额,净流入,大单：大于等于10万股或者20万元且小于50万股和100万元的成交单',
  `big_part_net_proportion` decimal(5,2) DEFAULT NULL COMMENT '大单净流入--净占比',
  `middle_part_net_inFlow_amount` decimal(12,4) DEFAULT NULL COMMENT '中单净额,净流入,中单：大于等于2万股或者4万元且小于10万股和20万元的成交单',
  `middle_part_net_proportion` decimal(5,2) DEFAULT NULL COMMENT '中单净流入--净占比',
  `litter_part_net_inFlow_amount` decimal(12,4) DEFAULT NULL COMMENT '小单净额,净流入,小单：小于2万股和4万元的成交单',
  `litter_part_net_proportion` decimal(5,2) DEFAULT NULL COMMENT '小单净流入--净占比',
  `stock_page` int(3) DEFAULT NULL COMMENT '第几页',
  `count_time` datetime DEFAULT NULL COMMENT '统计数据时间',
  `someInfo` longtext COMMENT '扩展数据',
  `time_version` varchar(64) DEFAULT NULL COMMENT '批次号',
  `crawler_version` varchar(64) DEFAULT NULL COMMENT '抓取版本，规则：股市#排行榜#股市闭市时间',
  `create_time` datetime DEFAULT NULL COMMENT '创建时间',
  `update_time` datetime DEFAULT NULL COMMENT '更新时间',
  PRIMARY KEY (`id`),
  KEY `idx_stock_code` (`stock_code`),
  KEY `idx_stock_name` (`stock_name`),
  KEY `idx_price_new` (`price_new`),
  KEY `idx_main_net_inflow_amount` (`main_net_inflow_amount`),
  KEY `idx_main_net_proportion` (`main_net_proportion`),
  KEY `idx_super_big_part_net_inFlow_amount` (`super_big_part_net_inFlow_amount`),
  KEY `idx_super_big_part_net_proportion` (`super_big_part_net_proportion`),
  KEY `idx_big_part_net_inFlow_amount` (`big_part_net_inFlow_amount`),
  KEY `idx_big_part_net_proportion` (`big_part_net_proportion`),
  KEY `idx_middle_part_net_inFlow_amount` (`middle_part_net_inFlow_amount`),
  KEY `idx_middle_part_net_proportion` (`middle_part_net_proportion`),
  KEY `idx_litter_part_net_inFlow_amount` (`litter_part_net_inFlow_amount`),
  KEY `idx_litter_part_net_proportion` (`litter_part_net_proportion`),
  KEY `idx_count_time` (`count_time`),
  KEY `idx_time_version` (`time_version`),
  KEY `idx_create_time` (`create_time`),
  KEY `idx_update_time` (`update_time`),
  KEY `idx_stock_market` (`stock_market`),
  KEY `idx_stock_rank` (`stock_rank`),
  KEY `idx_crawler_version` (`crawler_version`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COMMENT='东方财富-资金流向-个股资金流的数据'